### ISSUE TITLE
Не отображаются иконки роли в группе

### ISSUE THREAD

**Issue by IThoughtYouKnow** [Bunny67/ElvUI_Sirus#1]
Собсна проблема описана в заголовке.
![Screenshot_2](https://user-images.githubusercontent.com/42166757/64413651-3bb77100-d0d5-11e9-8db3-6c3a20d1b5b0.png)

**Comment by Bunny67** [comment]
![image](https://user-images.githubusercontent.com/5816685/64879375-8483a280-d65e-11e9-8b72-75e7497e5501.png)
Не могу воспроизвести.
Раньше она как то не работала, но фиксы были в основном ElvUI, скачай с последнего коммита, и должны работать.
