### ISSUE TITLE
Ошибки в LFD

### ISSUE THREAD

**Issue by Vitoshka** [Bunny67/ElvUI_Sirus#12]
**Description**
В инсте словил данные ошибки

**Version Number**
6.02

**Error Log**
**1x ElvUI_Sirus**-1.00\Modules\Skins\Blizzard\LFD.lua:194: attempt to index field 'texture' (a nil value)
ElvUI_Sirus-1.00\Modules\Skins\Blizzard\LFD.lua:208: in function <...ce\AddOns\ElvUI_Sirus\Modules\Skins\Blizzard\LFD.lua:207>
<in C code>: in function `LFDDungeonReadyDialogReward_SetReward'
Interface\FrameXML\LFDFrame.lua:625: in function `LFDDungeonReadyDialog_UpdateRewards':
Interface\FrameXML\LFDFrame.lua:592: in function `LFDDungeonReadyPopup_Update':
Interface\FrameXML\LFDFrame.lua:82: in function <Interface\FrameXML\LFDFrame.lua:80>:

Locals:
button = LFDDungeonReadyDialogRewardsFrameReward3 {
 rewardID = 2
 template = "Default"
 0 = <userdata>
}
dungeonID = 260
rewardIndex = 2
SkinLFDDungeonReadyDialogReward = <function> @ ElvUI_Sirus\Modules\Skins\Blizzard\LFD.lua:189:
GetLFGDungeonRewardLinkFix = <function> @ ElvUI_Sirus\Modules\Skins\Blizzard\LFD.lua:86:
unpack = <function> defined =[C]:-1
E = <table> {
 GetTimeInfo = <function> @ ElvUI\Core\Math.lua:303:
 mylevel = 80
 Bags = <table> {}
 resolution = "2560x1440"
 modules = <table> {}
 CancelTimer = <function> @ ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:161:
 FormatMoney = <function> @ ElvUI\Core\Math.lua:342:
 ExitVehicleShowFrames = <function> @ ElvUI\Core\API.lua:302:
 HelloKittyToggle = <function> @ ElvUI\Core\AprilFools.lua:362:
 CopyTable = <function> @ ElvUI\Core\Core.lua:489:
 DispelClasses = <table> {}
 SetMoversPositions = <function> @ ElvUI\Core\Movers.lua:482:
 ScheduleTimer = <function> @ ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:108:
 PriestColors = <table> {}
 RemoveEmptySubTables = <function> @ ElvUI\Core\Core.lua:505:
 SetupTheme = <function> @ ElvUI\Core\Install.lua:149:
 media = <table> {}
 UnlocalizedClassName = <function> @ ElvUI\Core\API.lua:27:
 data = <table> {}
 EnableBlizzardAddOns = <function> @ ElvUI\Core\Commands.lua:222:
 Role = "Melee"
 UIScale = <function> @ ElvUI\Core\PixelPerfect.lua:27:
 db = <table> {}
 FramesOverlap = <function> @ ElvUI\Core\Math.lua:107:
 SetEnabledState = <function> @ ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:455:
 Hook = <function> @ ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:274:
 Options = <table> {}
 Layout = <table> {}
 PluginInstaller = <table> {}
 PixelBestSize = <function> @ ElvUI\Core\PixelPerfect.lua:68:
 UnregisterEventForObject = <function> @ ElvUI\Core\Core.lua:988:
 Distributor = <table> {}
 SendPluginVersionCheck = <function> @ ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:145:
 HiddenFrame = <unnamed> {}
 Media = <table> {}
 UnregisterAllEvents = <function> @ Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:202:
 ScanTooltipTextures = <function> @ ElvUI\Core\API.lua:36:
 UIFrameFade = <function> @ ElvUI\Core\Animation.lua:215:
 MinimapWidth = 192
 StaticPopup_IsLastDisplayedFrame = <function> @ ElvUI\Core\StaticPopups.lua:561:
 Truncate = <function> @ ElvUI\Core\Math.lua:88:
 UpdateBackdropColors = <function> @ ElvUI\Core\Core.lua:416:
 TimeThreshold = 3
 ToggleMoveMode = <function> @ ElvUI\Core\Config.lua:55:
 RemoveTableDuplicates = <function> @ ElvUI\Core\Core.lua:526:
 name = "ElvUI"
 WorldMap = <table> {}
 MinimapHeight = 192
 Disable = <function> @ ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:345:
 TimeColors = <table> {}
 SlideOut = <function> @ ElvUI\Core\Animation.lua:150:
 Unhook = <function> @ ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:418:
 Print = <function> @ ElvUI\Core\Core.lua:183:
 Install = <function> @ ElvUI\Core\Install.lua:668:
 UnregisterObjectForVehicleLock = <function> @ ElvUI\Core\API.lua:274:
 RegisterCooldown = <function> @ ElvUI\Core\Cooldowns.lua:177:
 EscapeString = <function> @ ElvUI\Init.lua:110:
 TimeFormats = <table> {}
 RGBToHex = <function> defined @ElvUI\Core
  ---

**1x ElvUI_Sirus**-1.00\Modules\Skins\Blizzard\LFD.lua:194: attempt to index field 'texture' (a nil value)
ElvUI_Sirus-1.00\Modules\Skins\Blizzard\LFD.lua:208: in function <...ce\AddOns\ElvUI_Sirus\Modules\Skins\Blizzard\LFD.lua:207>
<in C code>: in function `LFDDungeonReadyDialogReward_SetReward'
Interface\FrameXML\LFDFrame.lua:625: in function `LFDDungeonReadyDialog_UpdateRewards':
Interface\FrameXML\LFDFrame.lua:592: in function `LFDDungeonReadyPopup_Update':
<string>:"*:OnShow":1: in function <[string "*:OnShow"]:1>
<in C code>: in function `Show'
Interface\FrameXML\StaticPopup.lua:4014: in function `StaticPopupSpecial_Show':
Interface\FrameXML\LFDFrame.lua:87: in function <Interface\FrameXML\LFDFrame.lua:80>:

Locals:
button = LFDDungeonReadyDialogRewardsFrameReward3 {
 rewardID = 2
 template = "Default"
 0 = <userdata>
}
dungeonID = 260
rewardIndex = 2
SkinLFDDungeonReadyDialogReward = <function> @ ElvUI_Sirus\Modules\Skins\Blizzard\LFD.lua:189:
GetLFGDungeonRewardLinkFix = <function> @ ElvUI_Sirus\Modules\Skins\Blizzard\LFD.lua:86:
unpack = <function> defined =[C]:-1
E = <table> {
 GetTimeInfo = <function> @ ElvUI\Core\Math.lua:303:
 mylevel = 80
 Bags = <table> {}
 resolution = "2560x1440"
 modules = <table> {}
 CancelTimer = <function> @ ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:161:
 FormatMoney = <function> @ ElvUI\Core\Math.lua:342:
 ExitVehicleShowFrames = <function> @ ElvUI\Core\API.lua:302:
 HelloKittyToggle = <function> @ ElvUI\Core\AprilFools.lua:362:
 CopyTable = <function> @ ElvUI\Core\Core.lua:489:
 DispelClasses = <table> {}
 SetMoversPositions = <function> @ ElvUI\Core\Movers.lua:482:
 ScheduleTimer = <function> @ ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:108:
 PriestColors = <table> {}
 RemoveEmptySubTables = <function> @ ElvUI\Core\Core.lua:505:
 SetupTheme = <function> @ ElvUI\Core\Install.lua:149:
 media = <table> {}
 UnlocalizedClassName = <function> @ ElvUI\Core\API.lua:27:
 data = <table> {}
 EnableBlizzardAddOns = <function> @ ElvUI\Core\Commands.lua:222:
 Role = "Melee"
 UIScale = <function> @ ElvUI\Core\PixelPerfect.lua:27:
 db = <table> {}
 FramesOverlap = <function> @ ElvUI\Core\Math.lua:107:
 SetEnabledState = <function> @ ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:455:
 Hook = <function> @ ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:274:
 Options = <table> {}
 Layout = <table> {}
 PluginInstaller = <table> {}
 PixelBestSize = <function> @ ElvUI\Core\PixelPerfect.lua:68:
 UnregisterEventForObject = <function> @ ElvUI\Core\Core.lua:988:
 Distributor = <table> {}
 SendPluginVersionCheck = <function> @ ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:145:
 HiddenFrame = <unnamed> {}
 Media = <table> {}
 UnregisterAllEvents = <function> @ Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:202:
 ScanTooltipTextures = <function> @ ElvUI\Core\API.lua:36:
 UIFrameFade = <function> @ ElvUI\Core\Animation.lua:215:
 MinimapWidth = 192
 StaticPopup_IsLastDisplayedFrame = <function> @ ElvUI\Core\StaticPopups.lua:561:
 Truncate = <function> @ ElvUI\Core\Math.lua:88:
 UpdateBackdropColors = <function> @ ElvUI\Core\Core.lua:416:
 TimeThreshold = 3
 ToggleMoveMode = <function> @ ElvUI\Core\Config.lua:55:
 RemoveTableDuplicates = <function> @ ElvUI\Core\Core.lua:526:
 name = "ElvUI"
 WorldMap = <table> {}
 MinimapHeight = 192
 Disable = <function> @ ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:345:
 TimeColors = <table> {}
 SlideOut = <function> @ ElvUI\Core\Animation.lua:150:
 Unhook = <function> @ ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:418:
 Print = <function> @ ElvUI\Core\Core.lua:183:
 Install = <function> @ ElvUI\Core\Install.lua:668:
 UnregisterObjectForVehicleLock = <function> @ ElvUI\Core\API.lua:274:
 RegisterCooldown = <function> @ ElvUI\Core\Cooldowns.lua:177:
 EscapeString = <function> @ ElvUI\Init.lua:110:
 TimeFormats = <table> {}
 RGBToHex = <function> defined @ElvUI\Core
  ---

**2x ElvUI_Sirus**-1.00\Modules\Skins\Blizzard\LFD.lua:194: attempt to index field 'texture' (a nil value)
ElvUI_Sirus-1.00\Modules\Skins\Blizzard\LFD.lua:208: in function <...ce\AddOns\ElvUI_Sirus\Modules\Skins\Blizzard\LFD.lua:207>
<in C code>: in function `LFDDungeonReadyDialogReward_SetReward'
Interface\FrameXML\LFDFrame.lua:625: in function `LFDDungeonReadyDialog_UpdateRewards':
Interface\FrameXML\LFDFrame.lua:592: in function `LFDDungeonReadyPopup_Update':
<string>:"*:OnEvent":4: in function <[string "*:OnEvent"]:1>

Locals:
button = LFDDungeonReadyDialogRewardsFrameReward3 {
 rewardID = 2
 template = "Default"
 0 = <userdata>
}
dungeonID = 260
rewardIndex = 2
SkinLFDDungeonReadyDialogReward = <function> @ ElvUI_Sirus\Modules\Skins\Blizzard\LFD.lua:189:
GetLFGDungeonRewardLinkFix = <function> @ ElvUI_Sirus\Modules\Skins\Blizzard\LFD.lua:86:
unpack = <function> defined =[C]:-1
E = <table> {
 GetTimeInfo = <function> @ ElvUI\Core\Math.lua:303:
 mylevel = 80
 Bags = <table> {}
 resolution = "2560x1440"
 modules = <table> {}
 CancelTimer = <function> @ ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:161:
 FormatMoney = <function> @ ElvUI\Core\Math.lua:342:
 ExitVehicleShowFrames = <function> @ ElvUI\Core\API.lua:302:
 HelloKittyToggle = <function> @ ElvUI\Core\AprilFools.lua:362:
 CopyTable = <function> @ ElvUI\Core\Core.lua:489:
 DispelClasses = <table> {}
 SetMoversPositions = <function> @ ElvUI\Core\Movers.lua:482:
 ScheduleTimer = <function> @ ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:108:
 PriestColors = <table> {}
 RemoveEmptySubTables = <function> @ ElvUI\Core\Core.lua:505:
 SetupTheme = <function> @ ElvUI\Core\Install.lua:149:
 media = <table> {}
 UnlocalizedClassName = <function> @ ElvUI\Core\API.lua:27:
 data = <table> {}
 EnableBlizzardAddOns = <function> @ ElvUI\Core\Commands.lua:222:
 Role = "Melee"
 UIScale = <function> @ ElvUI\Core\PixelPerfect.lua:27:
 db = <table> {}
 FramesOverlap = <function> @ ElvUI\Core\Math.lua:107:
 SetEnabledState = <function> @ ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:455:
 Hook = <function> @ ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:274:
 Options = <table> {}
 Layout = <table> {}
 PluginInstaller = <table> {}
 PixelBestSize = <function> @ ElvUI\Core\PixelPerfect.lua:68:
 UnregisterEventForObject = <function> @ ElvUI\Core\Core.lua:988:
 Distributor = <table> {}
 SendPluginVersionCheck = <function> @ ElvUI\Libraries\LibElvUIPlugin-1.0\LibElvUIPlugin-1.0.lua:145:
 HiddenFrame = <unnamed> {}
 Media = <table> {}
 UnregisterAllEvents = <function> @ Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:202:
 ScanTooltipTextures = <function> @ ElvUI\Core\API.lua:36:
 UIFrameFade = <function> @ ElvUI\Core\Animation.lua:215:
 MinimapWidth = 192
 StaticPopup_IsLastDisplayedFrame = <function> @ ElvUI\Core\StaticPopups.lua:561:
 Truncate = <function> @ ElvUI\Core\Math.lua:88:
 UpdateBackdropColors = <function> @ ElvUI\Core\Core.lua:416:
 TimeThreshold = 3
 ToggleMoveMode = <function> @ ElvUI\Core\Config.lua:55:
 RemoveTableDuplicates = <function> @ ElvUI\Core\Core.lua:526:
 name = "ElvUI"
 WorldMap = <table> {}
 MinimapHeight = 192
 Disable = <function> @ ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:345:
 TimeColors = <table> {}
 SlideOut = <function> @ ElvUI\Core\Animation.lua:150:
 Unhook = <function> @ ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:418:
 Print = <function> @ ElvUI\Core\Core.lua:183:
 Install = <function> @ ElvUI\Core\Install.lua:668:
 UnregisterObjectForVehicleLock = <function> @ ElvUI\Core\API.lua:274:
 RegisterCooldown = <function> @ ElvUI\Core\Cooldowns.lua:177:
 EscapeString = <function> @ ElvUI\Init.lua:110:
 TimeFormats = <table> {}
 RGBToHex = <function> defined @ElvUI\Core
  ---

**Comment by Bunny67** [comment]
Не могу воспроизвести, да и по коду все ок.

**Comment by Vitoshka** [comment]
Странно, что с кодом всё норм, где то конфликт, ошибки ловлю именно в инсте (героике), при реге рандом инста, внутри самого инста
очень досаждают эти 3 ошибки, причём их много вылазит в процессе инста

**Comment by Vitoshka** [comment]
Что заметил также, эти ошибки появились недавно, после обновлений на ElvUi 3.3.5 связанных с текстурами скинов

**Comment by Vitoshka** [comment]
После фикса сегодня в инсте снова ошибки, как только рандом зарегали инст в группе

4x ElvUI_Sirus-1.00\Modules\Skins\Blizzard\LFD.lua:218: attempt to index field 'texture' (a nil value)
<in C code>: in function `LFDDungeonReadyDialogReward_SetReward'
Interface\FrameXML\LFDFrame.lua:625: in function `LFDDungeonReadyDialog_UpdateRewards':
Interface\FrameXML\LFDFrame.lua:592: in function `LFDDungeonReadyPopup_Update':
<string>:"*:OnEvent":4: in function <[string "*:OnEvent"]:1>

Locals:
(*temporary) = <function> defined =[C]:-1
 = <function> @ Interface\FrameXML\LFDFrame.lua:651:
 = <function> @ ElvUI_Sirus\Modules\Skins\Blizzard\LFD.lua:207:

  ---

2x ElvUI_Sirus-1.00\Modules\Skins\Blizzard\LFD.lua:218: attempt to index field 'texture' (a nil value)
<in C code>: in function `LFDDungeonReadyDialogReward_SetReward'
Interface\FrameXML\LFDFrame.lua:625: in function `LFDDungeonReadyDialog_UpdateRewards':
Interface\FrameXML\LFDFrame.lua:592: in function `LFDDungeonReadyPopup_Update':
<string>:"*:OnShow":1: in function <[string "*:OnShow"]:1>
<in C code>: in function `Show'
Interface\FrameXML\StaticPopup.lua:4014: in function `StaticPopupSpecial_Show':
Interface\FrameXML\LFDFrame.lua:87: in function <Interface\FrameXML\LFDFrame.lua:80>:

Locals:
(*temporary) = <function> defined =[C]:-1
 = <function> @ Interface\FrameXML\LFDFrame.lua:651:
 = <function> @ ElvUI_Sirus\Modules\Skins\Blizzard\LFD.lua:207:

  ---

9x ElvUI_Sirus-1.00\Modules\Skins\Blizzard\LFD.lua:218: attempt to index field 'texture' (a nil value)
<in C code>: in function `LFDDungeonReadyDialogReward_SetReward'
Interface\FrameXML\LFDFrame.lua:625: in function `LFDDungeonReadyDialog_UpdateRewards':
Interface\FrameXML\LFDFrame.lua:592: in function `LFDDungeonReadyPopup_Update':
Interface\FrameXML\LFDFrame.lua:82: in function <Interface\FrameXML\LFDFrame.lua:80>:

Locals:
(*temporary) = <function> defined =[C]:-1
 = <function> @ Interface\FrameXML\LFDFrame.lua:651:
 = <function> @ ElvUI_Sirus\Modules\Skins\Blizzard\LFD.lua:207:

  ---
