### ISSUE TITLE
WatchFrame

### ISSUE THREAD

**Issue by iseos** [Bunny67/ElvUI_Sirus#16]
Адаптировал скин слежения за квестами (из ElvUI/Modules/Skins/Blizzard/WatchFrame.lua)
[WatchFrame.lua Gist](https://gist.github.com/iseos/5cd135796f25e62149939db31cffba85)
![WoWScrnShot_092919_184244](https://user-images.githubusercontent.com/16374845/65834967-5b634300-e2e9-11e9-9622-02a8529a542f.jpg)
Но как убрать текстуру заголовка, по идее это WatchFrameHolder
![WoWScrnShot_092919_184249](https://user-images.githubusercontent.com/16374845/65835091-d416cf00-e2ea-11e9-9447-28c66eead932.jpg)
Но 'WatchFrameHolder' имеет значение nil

Может быть подскажешь по этому что-нибудь, название фрейма

**Comment by Bunny67** [comment]
```
WatchFrame.BlocksFrame.QuestHeader:StripTextures()
WatchFrame.BlocksFrame.AchievementHeader:StripTextures()
```

**Comment by Bunny67** [comment]
@iseos Кинул инвайт на репу, что бы реквесты не создавать. Так как не всегда смотрю репу :)

**Comment by iseos** [comment]
@Bunny67 Окей, спасибо.
