### ISSUE TITLE
Отсутствуют текстуры ElvUi

### ISSUE THREAD

**Issue by Vitoshka** [Bunny67/ElvUI_Sirus#2]
**Description**
Отсутствуют некоторые текстуры

**Version Number**
6.04

![WoWScrnShot_100319_193142](https://user-images.githubusercontent.com/30943063/66147142-e5c3e380-e616-11e9-87e9-d0fb1c775f38.jpg)
![WoWScrnShot_100119_004834](https://user-images.githubusercontent.com/30943063/65963554-abfeab80-e463-11e9-88e6-6d46b0612d2b.jpg)

**Comment by Bunny67** [comment]
Скины всех фреймов не скоро появятся, так как даже на основной елв времени не хватает. Да и я знаю что не заскиненно.
