### ISSUE TITLE
Скрытие бафа осени и А/О дебафов

### ISSUE THREAD

**Issue by gamer4eg** [Bunny67/ElvUI_Sirus#21]
Добавь плз еще галку на скрытие бафа осени(+35%опыта и 5%репы), 
а так же дебафов Альянс и Орда.
Не люблю когда всякая юзлесная хрень в бафах/дебафах показывается.
АЛСО смог скрыть дебаф альянса и орды тупо дописав их в код после премиума.
А вот баф так не скрывается. Если влом фиксить-подскажи хоть как его скрыть плез.

**Comment by gamer4eg** [comment]
А вообще хотелось бы в бафах и дебафах возможность привязать к ним фильтр.
Так было бы намного проще.
Сделать отдельнфй фильтр и скрыть все мешающие бафы/дебафы.

**Comment by gamer4eg** [comment]
![image](https://user-images.githubusercontent.com/23147230/99821097-a5009400-2b62-11eb-8fb6-b75ae160c4d1.png)
этот например

**Comment by Bunny67** [comment]
Создай отдельный фильтр с типом Черный список, и туда добавляй ауры. Ну и примени его для баффов или дедаффов

**Comment by gamer4eg** [comment]
Как его к миникарте то применить? Фильтр можно к фреймам применить, а вот к бафам/дебафам у миникарты как?

**Comment by gamer4eg** [comment]
![image](https://user-images.githubusercontent.com/23147230/99842973-d50b5f80-2b81-11eb-9307-4eb3c760542e.png)

**Comment by gamer4eg** [comment]
![image](https://user-images.githubusercontent.com/23147230/99843072-fcfac300-2b81-11eb-83b8-930e9e11a076.png)

**Comment by Bunny67** [comment]
Обнови этот плагин, я добавил в настройки баффов и дебаффов

**Comment by gamer4eg** [comment]
Спасибо! Ты лучший!
