### ISSUE TITLE
Авто нидераст ^_^

### ISSUE THREAD

**Issue by gamer4eg** [Bunny67/ElvUI_Sirus#22]
В реалиях ПП на х3 кроме автоматического неоткажус/распылить нужен еще авто нидераст.
Те если можно нажать нид-жмет нид.
Если можно нажать распылить И нид-жмет распил.
Заранее спасибо. И да, примкни ко злу!.. у нас есть печеньки.
А еще настройку туда-нидить всегда(для чантеров)

**Comment by iseos** [comment]
Этого не будет.
