### ISSUE TITLE
Ошибка ElvUi_Sirus

### ISSUE THREAD

**Issue by Vitoshka** [Bunny67/ElvUI_Sirus#4]
**Description**
Переодически возникает такая ошибка

**Version Number**
6.01

**Error Log**
1x ElvUI_Sirus-1.00\Modules\Skins\Blizzard\LFD.lua:460: attempt to index field 'Background' (a nil value)
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function ?'
CallbackHandler-1.0-6 (Ace3):92: in functionFire'
ElvUI-6.01\Modules\Skins\Skins.lua:693: in function Initialize'
ElvUI-6.01\Modules\Skins\Skins.lua:700: in function <ElvUI\Modules\Skins\Skins.lua:699>
CallbackHandler-1.0-6 (Ace3):157: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:157>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function?'
CallbackHandler-1.0-6 (Ace3):92: in function Fire'
ElvUI-6.01\Core\Core.lua:1047: in functionCallLoadedModule'
ElvUI-6.01\Core\Core.lua:1072: in function InitializeModules'
ElvUI-6.01\Core\Core.lua:1223: in functionInitialize'
ElvUI-6.01\Init.lua:204: in function <ElvUI\Init.lua:203>

**Comment by Bunny67** [comment]
16 дней назад были 2 коммита на этот фикс, из за нового фрейма. Щас ошибки не должно быть.
