### ISSUE TITLE
Ошибки с ilvl (возможно проблема именно из-за Sirus)

### ISSUE THREAD

**Issue by Vitoshka** [Bunny67/ElvUI_Sirus#6]
**Description**
Возможно данные ошибки именно из-за особенностей сервера, можно их как -то пож. проверить, очень досождают, особенно в рейде, группе

писал в данной теме https://github.com/ElvUI-WotLK/ElvUI_Enhanced/issues/71

**Version Number**
6.01

**Error Log**
85x ElvUI_Enhanced-1.03\Modules\Misc\equipmentInfo.lua:65: attempt to index field 'ItemLevel' (a nil value)
ElvUI_Enhanced-1.03\Modules\Misc\equipmentInfo.lua:148: in function ?' CallbackHandler-1.0-6 (Ace3):147: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:147> <string>:"safecall Dispatcher[2]":4: in function <[string "safecall Dispatcher[2]"]:4> <in C code>: ? <string>:"safecall Dispatcher[2]":13: in function ?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
AceEvent-3.0-4:120: in function <...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

1x ElvUI_Enhanced-1.03\Modules\Misc\equipmentInfo.lua:65: attempt to index field 'ItemLevel' (a nil value)
ElvUI_Enhanced-1.03\Modules\Misc\equipmentInfo.lua:151: in function OnEvent' ElvUI_Enhanced-1.03\Modules\Misc\equipmentInfo.lua:44: in function <...AddOns\ElvUI_Enhanced\Modules\Misc\equipmentInfo.lua:44> <string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4> <in C code>: ? <string>:"safecall Dispatcher[1]":13: in function ?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
AceEvent-3.0-4:120: in function <...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Bunny67** [comment]
Переустанови ElvUI_Enhanced полностью, то есть полностью удали папку и добавь по новой. Так как то что в репе не совпадает с твоей ошибкой. Возможно это из за ренейма файлов, в аддоне.

**Comment by Vitoshka** [comment]
Попробую, пока спокойно, если что-то будет, сообщу

**Comment by Bunny67** [comment]
Ну ошибок не должно быть, так как плагин equipmentInfo правили и под сирус.
