### ISSUE TITLE
Не отображается вертикальная полоса в фиксаторах

### ISSUE THREAD

**Issue by Vitoshka** [Bunny67/ElvUI_Sirus#7]
**Description**
Не отображается вертикальная красная полоса во включённых фиксаторах, возможно это связано с [ElvUi](https://github.com/ElvUI-WotLK/ElvUI)

**Version Number**
6.01

![WoWScrnShot_091319_212044](https://user-images.githubusercontent.com/30943063/64885343-94a27e80-d66c-11e9-81e4-8e5a48f3a351.jpg)

**Comment by Bunny67** [comment]
Она может пропадать из за какстомного масштаба, либо разрешения, либо из за оконного режима. Это не исправить, так как размер окна вов не узнать.
