### ISSUE TITLE
Нужна незначительная текстура для видимой части управления рейдом

### ISSUE THREAD

**Issue by Vitoshka** [Bunny67/ElvUI_Sirus#9]
**Description**
Сделайте пож. данную небольшую текстурку, с возможностью перемещения этой текстуры через фиксаторы по возможности, 
![WoWScrnShot_091519_213532](https://user-images.githubusercontent.com/30943063/64928088-edfce000-d81b-11e9-8a99-b273fa72d9b7.jpg)
![WoWScrnShot_091519_213536](https://user-images.githubusercontent.com/30943063/64928089-edfce000-d81b-11e9-9a35-2f202ea3a5bc.jpg)

уж очень она выбивается из общего фона стиля ElvUi, причём она на виду
(наводка, похожие текстуры и изменение функций в Raid Control в ElvUi)
![WoWScrnShot_091619_005013](https://user-images.githubusercontent.com/30943063/64928099-374d2f80-d81c-11e9-9ef3-c95c6bc58c2c.jpg)

**Version Number**
6.01

**Comment by iseos** [comment]
[3393841](https://github.com/Bunny67/ElvUI_Sirus/commit/339384146d5c3c0eb1b6e36c330e3a905b2056d3)

![WoWScrnShot_100119_193519](https://user-images.githubusercontent.com/16374845/65982908-078d6100-e485-11e9-8f6f-3c666aeb30f8.jpg)

**Comment by Vitoshka** [comment]
> [3393841](https://github.com/Bunny67/ElvUI_Sirus/commit/339384146d5c3c0eb1b6e36c330e3a905b2056d3)
> 
> ![WoWScrnShot_100119_193519](https://user-images.githubusercontent.com/16374845/65982908-078d6100-e485-11e9-8f6f-3c666aeb30f8.jpg)

Спасибо за текстуру, но нужно незначительный апгрейд:
1) Есть ли возможность сделать отображение иконок в 3D?
пример:
![WoWScrnShot_100119_200346](https://user-images.githubusercontent.com/30943063/65983887-399fc280-e487-11e9-968d-e7aca074375c.jpg)
Эти иконки уже встроены в ElVUi
2) Выравнять слова Создать рейд, Готовность и Флажок (и если есть возможность, сделать флажок более чётким) по центру ячеек в которых они находятся
3) Сделать чуть уже и более светлыми, кнопки _сокрытия_ и _передвигания_ фрейма

Спасибо

**Comment by iseos** [comment]
1. Окей.
2. По вертикали или горизонтали? Вот с флажком проблема, надо искать текстуру, я взял ту что была в ElVUi.
3. Просто сделать светлее, а то что на них нет текстур нормально? Пытался добавить стрелочки но выглядело не очень, решил отказаться.

**Comment by Vitoshka** [comment]
> 1. Окей.
> 2. По вертикали или горизонтали? Вот с флажком проблема, надо искать текстуру, я взял ту что была в ElVUi.
> 3. Просто сделать светлее, а то что на них нет текстур нормально? Пытался добавить стрелочки но выглядело не очень, решил отказаться.

2) по горизонтали (отцентрировать). Можно любой флажок в стиле Elva, чтобы он только был чётким
3) пример откуда взять иконку
![WoWScrnShot_100119_203719](https://user-images.githubusercontent.com/30943063/65986255-28a58000-e48c-11e9-9656-ce584fcdd28a.jpg)
Текстура вниз иконка внизу 
![WoWScrnShot_100119_2037110](https://user-images.githubusercontent.com/30943063/65986330-4a9f0280-e48c-11e9-9aab-b8f6e81a1e71.jpg)
Текстура сбоку (панель развёрнута)
![WoWScrnShot_100119_2037112](https://user-images.githubusercontent.com/30943063/65986356-5be80f00-e48c-11e9-9b74-18d60eea1991.jpg)
Текстура сбоку (панель свёрнута)
![WoWScrnShot_100119_2037111](https://user-images.githubusercontent.com/30943063/65986375-673b3a80-e48c-11e9-90d7-f144ed8e26c4.jpg)
Общая прозрачность этих стрелок с фоном _чуть более_ темнее чем фон где иконки меток

**Comment by Vitoshka** [comment]
![WoWScrnShot_100119_213900](https://user-images.githubusercontent.com/30943063/65990629-9bb2f480-e494-11e9-8fcb-acb63b801e6a.jpg)
Нет текстуры и можно ли уменьшить толщину бокового фрейма и сделать их одинаковыми (нижний и боковой), а также добавить стрелочку вниз на нижнем якоре

**Comment by Vitoshka** [comment]
Также текст не выровнялся по центру (слово Создать рейд и слово готовность)

**Comment by Bunny67** [comment]
Текст на кнопках не поправить. Остальное вроде все поправил

**Comment by iseos** [comment]
@Bunny67, спасибо. Отлично получилось.
А на счет выравнивания:
![WoWScrnShot_100119_221332](https://user-images.githubusercontent.com/16374845/65992964-f1899b80-e498-11e9-95ca-5d9d1370c645.jpg)
Текст расположен ровно относительно кнопки в которой находится.

**Comment by Bunny67** [comment]
Он наверн имел ввиду по Y-ку
